backend:
  name: git-gateway
  repo: JJNoCode/Test
  branch: main
  identity_url: https://auth.decapbridge.com/sites/64ff3bee-62f8-48da-afd6-901a38cbb163
  gateway_url: https://gateway.decapbridge.com

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Accueil"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
